# Generated by Django 4.0.5 on 2022-06-27 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cli', models.CharField(max_length=100)),
                ('nasc_cli', models.DateField()),
                ('cpf_cli', models.IntegerField()),
                ('tel_cli', models.CharField(max_length=15)),
                ('email_cli', models.EmailField(max_length=254)),
                ('sex_cli', models.CharField(max_length=1)),
                ('dt_cadastro', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fun', models.CharField(max_length=100)),
                ('cpf_fun', models.IntegerField()),
                ('tel_fun', models.CharField(max_length=15)),
                ('email_fun', models.EmailField(max_length=254)),
                ('status_fun', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ser', models.CharField(max_length=20)),
                ('desc_ser', models.TextField(verbose_name='Descrição')),
                ('val_ser', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ag', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agendador.cliente')),
                ('profis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agendador.funcionario')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agendador.servico')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
