# Generated by Django 4.0.5 on 2022-06-29 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agendador', '0002_remove_agendamento_cliente_remove_agendamento_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_ag',
            field=models.DateTimeField(),
        ),
    ]
